# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iuJaWAcH9J20Qr5cx9CHDXLDDywcncca
"""

a=10
b=20
c=a+b
print(c)

c=int(input("Enter a number"))
if c%2==0:
  print("number is even")
else:
    print("number is odd")

def prime():
  num=int(input("Enter a number"))
  if num<=1:
    print("It is not a prime number")
    return
  for i in range(2,int(num**0.5)+1):
    if num%i==0:
      print("It is not a prime number")
      return
  print("It is a prime number")
prime()

a=10
b=5
c=6
d=8
print(max(a,b,c,d))

c=int(input("Enter number to find factorial:"))
for i in range(1,c):
  c=c*i
print(c)

num_str = input("Enter a number: ")
try:
    num = int(num_str)
    reversed_num = 0
    is_negative = False
    if num < 0:
        is_negative = True
        num = abs(num)
    while num > 0:
        last_digit = num % 10
        reversed_num = (reversed_num * 10) + last_digit
        num //= 10
    if is_negative:
        reversed_num *= -1
    print("Reversed number:", reversed_num)
except ValueError:
    print("Invalid input. Please enter an integer.")

x=input("Enter a string:")
if x==x[::-1]:
  print("It is a palindrome")
else:
  print("It is not a palindrome")

x=int(input("Enter a number:"))
sum=0
while x>0:
  sum=sum+x%10
  x=x//10
print(sum)

n=int(input("Enter a table:"))
for i in range(1,11):
  print(n,"*",i,"=",n*i)

print("operations: +,-,*,/")
while True:
  op=input("Enter operation:")
  if op=="+":
    a=int(input("Enter first number:"))
    b=int(input("Enter second number:"))
    print(a+b)
  elif op=="-":
    a=int(input("Enter first number:"))
    b=int(input("Enter second number:"))
    print(a-b)
  elif op=="*":
    a=int(input("Enter first number:"))
    b=int(input("Enter second number:"))
    print(a*b)
  elif op=="*/":
    a=int(input("Enter first number:"))
    b=int(input("Enter second number:"))
    print(a/b)
  else:
      break

x=int(input("Enter number of rows:"))
for i in range(1,x+1):
  print("*"*i)

